/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\engine.glb 
Author: Prabhu Ram (https://sketchfab.com/virtualmakes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wam-4-indian-electric-engine-locomotive-37aa5b915f9a4e44825da1c8a498a850
Title: WAM-4 | Indian Electric Engine Locomotive
// */

// import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Engine(props) {
  const { nodes, materials } = useGLTF('/engine.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={84.447}>
        <group position={[11.417, -4.793, 3.163]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert2SG} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert6SG} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert6SG} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.TRAIN_workfile_mayaTRAIN_workfile_mayalambert6SG} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.TRAIN_workfile_mayalambert1SG} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.initialShadingGroup} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.lambert3SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/engine.glb')
